-- ============================================================
-- 3_계약-취소 시트 형식 — 취소된 계약 내역
-- ============================================================

SELECT
    ROW_NUMBER() OVER (ORDER BY CA.UPDATED_AT) AS "SEQ",
    CASE
        WHEN CA.SUBSCRIPTION_TYPE = 'DEALER_APP' THEN '딜러앱'
        WHEN CA.SUBSCRIPTION_TYPE = 'CS'         THEN 'CS'
        WHEN CA.SUBSCRIPTION_TYPE = 'RENEWAL'    THEN '갱신'
        ELSE '기타'
    END AS "영업채널",
    C.CUSTOMER_NAME AS "고객명",
    C.CUSTOMER_PHONE_NUMBER AS "연락처",
    COALESCE(CV.LICENSE_PLATE_NUMBER, CV.VIN) AS "차량번호",
    CV.EXIST_INSURANCE_END_DT AS "만기일자",
    LPAD(MONTH(CV.EXIST_INSURANCE_END_DT), 2, '0') || '월' AS "만기월",
    CV.CONTRACT_AMOUNT AS "보험료",
    CA.JOIN_INSURER_CODE AS "가입보험사",
    CASE
        WHEN CA.CHANNEL_PATH LIKE '%CM%' THEN 'CM'
        WHEN CA.CHANNEL_PATH LIKE '%TM%' THEN 'TM'
        ELSE CA.CHANNEL_PATH
    END AS "가입경로",
    CA.JOIN_COMPLETED_AT::DATE AS "체결일자",
    TO_CHAR(CA.JOIN_COMPLETED_AT, 'YY') || '-' || LPAD(MONTH(CA.JOIN_COMPLETED_AT), 2, '0') || 'm' AS "체결월",
    m.NAME AS "체결/담당매니저",
    u.USER_NAME AS "딜러이름",
    u.USER_ID AS "딜러ID",
    u.PRIMARY_AFFILIATION AS "딜러브랜드",
    CA.UPDATED_AT::DATE AS "취소일자"
FROM AJDCAR_PROD.PUBLIC.COUNSEL_APPLICATION CA
JOIN AJDCAR_PROD.PUBLIC.CUSTOMER C
     ON C.CUSTOMER_ID = CA.CUSTOMER_ID AND C.IS_DELETED = FALSE
JOIN AJDCAR_PROD.PUBLIC.COUNSEL_VEHICLE CV
     ON CV.COUNSEL_ID = CA.COUNSEL_ID AND CV.IS_DELETED = FALSE
LEFT JOIN AJDCAR_PROD.PUBLIC.USERS u
     ON u.ID = CA.USER_ID
LEFT JOIN AJDCAR_PROD.PUBLIC.MANAGER m
     ON m.ID = CA.COUNSEL_MANAGER_ID
WHERE CA.IS_DELETED = FALSE
  AND CA.COUNSEL_STATUS = 'JOIN_CANCELLED'
ORDER BY CA.UPDATED_AT;
